In [1]:
import numpy as np

In [2]:
i_e = np.array([2,1])
w_e1 = np.array([[2,1,-1],[-2,-4,1]])
b_e1 = np.array([1,-1,2])
w_e2 = np.array([[-2,3],[3,-1],[5,0]])
b_e2 = np.array([0,-1])

In [3]:
i_eW = np.dot(i_e,w_e1)
i_eW

array([ 2, -2, -1])

In [4]:
i_eW += b_e1
i_eW

array([ 3, -3,  1])

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [14]:
g1 = sigmoid(i_eW)
g1=np.round(g1,3)
g1

array([0.953, 0.047, 0.731])

In [15]:
g1W = np.dot(g1,w_e2)
print(np.round(g1W,4))

[1.89  2.812]


In [16]:
g1W += b_e2
g1W

array([1.89 , 1.812])

In [17]:
g2 = sigmoid(g1W)
g2 = np.round(g2,3)
g2

array([0.869, 0.86 ])

###### Exercises 1
* (i) (1,0, 2, -3)

In [18]:
i1 = np.array([1,0,2,-3])
W1 = np.array([[4,-5,0,1],[-3,6,-1,2],[0,1,1,-2],[2,0,-3,4]])
b1 = np.array([1,-2,0,-1])
W2 = np.array([[-2,1],[-1,0],[1,-3],[5,-1]])
b2 = np.array([-2,2])

In [21]:
hidden1 = sigmoid(np.dot(i1,W1)+b1)
output1 = sigmoid(np.dot(hidden1,W2)+b2)
print("hidden layer1:", np.round(hidden1,3))
print("output layer1:", np.round(output1,3))

hidden layer1: [0.269 0.007 1.    0.   ]
output layer1: [0.176 0.325]


* (ii) (-2,3,1,0)

In [23]:
i2 = np.array([-2,3,1,0])
hidden2 = sigmoid(np.dot(i2,W1)+b1)
output2 = sigmoid(np.dot(hidden2,W2)+b2)
print("hidden layer2:", np.round(hidden2,3))
print("output layer2:", np.round(output2,3))

hidden layer2: [0.    1.    0.119 0.731]
output layer2: [0.684 0.713]


* (iii) (1,0,1,1)

In [24]:
i3 = np.array([1,0,1,1])
hidden3 = sigmoid(np.dot(i3,W1)+b1)
output3 = sigmoid(np.dot(hidden3, W2)+b2)
print("hidden layer3", np.round(hidden3,3))
print("output layer3", np.round(output3,3))

hidden layer3 [0.999 0.002 0.119 0.881]
output layer3 [0.628 0.853]


#### (b) activation funtion relu at each node

In [26]:
def relu(x):
    return np.maximum(0,x)

In [27]:
hidden1 = relu(np.dot(i1,W1)+b1)
output1 = relu(np.dot(hidden1,W2)+b2)
print("hidden layer1:", np.round(hidden1,3))
print("output layer1:", np.round(output1,3))

hidden layer1: [ 0  0 11  0]
output layer1: [9 0]


In [28]:
i2 = np.array([-2,3,1,0])
hidden2 = relu(np.dot(i2,W1)+b1)
output2 = relu(np.dot(hidden2,W2)+b2)
print("hidden layer2:", np.round(hidden2,3))
print("output layer2:", np.round(output2,3))

hidden layer2: [ 0 27  0  1]
output layer2: [0 1]


In [30]:
i3 = np.array([1,0,1,1])
hidden3 = relu(np.dot(i3,W1)+b1)
output3 = relu(np.dot(hidden3, W2)+b2)
print("hidden layer3", np.round(hidden3,3))
print("output layer3", np.round(output3,3))

hidden layer3 [7 0 0 2]
output layer3 [0 7]


##### (c) use relu at hidden layer, and sigmoid at output

In [31]:
hidden1 = relu(np.dot(i1,W1)+b1)
output1 = sigmoid(np.dot(hidden1,W2)+b2)
print("hidden layer1:", np.round(hidden1,3))
print("output layer1:", np.round(output1,3))

hidden layer1: [ 0  0 11  0]
output layer1: [1. 0.]


In [32]:
i2 = np.array([-2,3,1,0])
hidden2 = relu(np.dot(i2,W1)+b1)
output2 = sigmoid(np.dot(hidden2,W2)+b2)
print("hidden layer2:", np.round(hidden2,3))
print("output layer2:", np.round(output2,3))

hidden layer2: [ 0 27  0  1]
output layer2: [0.    0.731]


In [34]:
i3 = np.array([1,0,1,1])
hidden3 = relu(np.dot(i3,W1)+b1)
output3 = sigmoid(np.dot(hidden3, W2)+b2)
print("hidden layer3", np.round(hidden3,3))
print("output layer3", np.round(output3,3))

hidden layer3 [7 0 0 2]
output layer3 [0.002 0.999]


##### (2) Consider a network with 2 inputs, 3 nodes in first hidden layer, 3 nodes in second  hidden layer, and 2 outputs nodes

In [35]:
W_1 = np.array([[1,-1,0],[-2,4,-1]])
W_2 = np.array([[2,0,-1],[1,-2,-3],[5,0,0]])
W_3 = np.array([[0,2],[-1,-1],[4,-3]])
b_1 = np.array([0,-3,2])
b_2 = np.array([3,3,-1])
b_3 = np.array([0,1])

* use relu function
* (i) (1,-1)

In [42]:
input_i = np.array([1,-1])

In [43]:
layer1_inp = input_i
layer1_output = relu(np.dot(layer1_inp, W_1) +b_1)
layer2_output  = relu(np.dot(layer1_output, W_2)+ b_2)
output = relu(np.dot(layer2_output, W_3) + b_3)

In [44]:
output

array([ 0, 46])

* (ii) (3,-2)

In [45]:
input_ii = np.array([3,-2])
layer1_output = relu(np.dot(input_ii, W_1) +b_1)
layer2_output  = relu(np.dot(layer1_output, W_2)+ b_2)
output_ii = relu(np.dot(layer2_output, W_3) + b_3)
output_ii

array([ 0, 72])

#### (b) Using sigmoid function for the same inputs as  above

In [47]:
layer1_inp = input_i
layer1_output = sigmoid(np.dot(layer1_inp, W_1) +b_1)
layer2_output  = sigmoid(np.dot(layer1_output, W_2)+ b_2)
output = sigmoid(np.dot(layer2_output, W_3) + b_3)
output

array([0.38796133, 0.84221994])

In [48]:
input_ii = np.array([3,-2])
layer1_output = sigmoid(np.dot(input_ii, W_1) +b_1)
layer2_output  = sigmoid(np.dot(layer1_output, W_2)+ b_2)
output_ii = sigmoid(np.dot(layer2_output, W_3) + b_3)
output_ii

array([0.38334351, 0.84414937])